---
#python3 -c 'import crypt; print(crypt.crypt("password"))'
#ruby -e 'puts "password".crypt("$6$saltsalt$")'

- hosts: app 
  become: yes
  ### You can define varibale Likethis
  vars:
    - user_root: root
    - user_admin: luneareth
    - user_app: app
    - password_admin: "$6$.0CZTdQSV4ITGihp$Ie6QjQ0q7KrBpIZ0N5QxPyBI1f1TtaeGgJgLtztFj9qT57LmIamQR2vgHiHE37T6iix3dYPaRWY5Jufxp6xUY1"
    - password_app: "$6$saltsalt$/uq1M8rxctPrewYHtQt/jyqEBc.Hez15erl8qFp/QhkRUB2QpJqqdsi77hyRJHWwDaswicTrH1vV71UeqMvVO."
    - password_root: "$6$saltsalt$z2yY4VhG4KAz11bQArkp24S8Y73ZUChMJA881glm24msCVXD5Lty6cxhmX1JhRxTqPaQBKe2J4aq4pDCcG9BG1"
    - public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdA4sdMITuL88nV4XP44MF/uvUwoSl08ExgRE3xNdUsIZaSa+VeNiLVwZGoGdvQf6F5CYSXl4kpUyQZspYQvu+H6VEU/bhYvHFHok+BLZPLg9IJERCK8l/8tnRRv3DllSFGx9zSTEaAy6mA3JiObNwf0WmnWkmFMKroqkvV+ss/PUCQvYbLkmUXuaAgDISisj0YYYk8eFg8RdDxk0Z5T8UrO4Gm7NTH6T/BtXP5UATHmDIG/jWMS+tn6PKh/pXpq6oS/epx3Uyz38h8p6Hjs/Xlo1c6989uDqh+035bX7vGYpWcBlq3UsYOMHP7vmqm6yUOV8fUyvK0D7MmtQuLVNI72fjbqkFM+REQ7RniXi9WqgzTEgL0WYtbGa0bTvBxwu6QkhDXucr8fCFKQ3+9I4LzXEz6aobRw7N0Myi/rltqcVbNJb9hc3uHggXvhINu/wQfoIcxK2lWUXPapR07Lzs8pIT6miv/r5A9rgztFViPwe1MkFlqGoEWYgbtCZuT9E= neareth@127block"
  ### Or Define using file external
  #vars_files:
  #  - ./global_variables.yml
  ### Or Define Variable as Host Or Group in inventories/production/group_vars/app
  roles: 
    - luneareth_iam

