- name: Install Tools 
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - curl
    - wget
    - screen
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags:
    - croncat_packages
    - croncat_packages_install_tools
## curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
## sudo yum install yarn
- name: Install Repo NodeJS
  shell: curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags:
    - croncat_packages
    - croncat_packages_install_repo_nodejs

- name: Install NodeJS
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - nodejs
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags:
    - croncat_packages
    - croncat_packages_install_nodejs

- name: Check NodeJS Version
  shell: node --version
  register: is_nodejs_version
  tags:
    - croncat_packages

- name: Display NodeJS Version
  debug:
    var: is_nodejs_version.stdout
  tags:
    - croncat_packages
    - croncat_packages_show_nodejs_version




  