- name: add motd
  become: 'yes'
  template:
    src: motd.j2
    dest: /etc/motd
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - banner
    - motd

- name: add issue and issue.net
  become: 'yes'
  template:
    src: issue.j2
    dest: "{{ item }}"
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  with_items:
    - /etc/issue
    - /etc/issue.net
  tags: 
    - banner
    - issue