- name: Create Directory For Pool Report
  file:
    path: /opt/security_report/
    state: directory
    owner: root
    group: root
    mode: 700
  tags:
    - iam-cronjob


- name: Cronjob Check Daily Aide RPM Based
  cron:
      name: "Aide Check Daily"
      minute: "23"
      hour: "22"
      day: "*"
      month: "*"
      weekday: "*"
      job: "/usr/sbin/aide --check >> /opt/security_report/aide.`date +%m-%d-%y_%H-%M'`.log"
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags: 
     - iam-cronjob
   

- name: Cronjob Check Daily Aide Deb Based
  cron:
      name: "Aide Check Daily"
      minute: "23"
      hour: "22"
      day: "*"
      month: "*"
      weekday: "*"
      job: "aide -c /etc/aide/aide.conf -C >> /opt/security_report/aide.`date +'%m-%d-%y_%H-%M'`.log"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
  tags: 
    - iam-cronjob
    

- name: Cronjob Check Malware
  cron:
      name: "rkhunter checker"
      minute: "23"
      hour: "22"
      day: "*"
      month: "*"
      weekday: "*"
      job: "rkhunter -c --skip-keypress >> /opt/security_report/rkhunter.`date +'%m-%d-%y_%H-%M'`.log"
  tags: 
    - iam-cronjob
   

- name: crontab ram flush
  cron:
    name: "ram flush"
    job: "bash /opt/crontab/ram_flush.sh >> /opt/security_report/ram_flush.`date +'%m-%d-%y_%H-%M'`.log"
  register: check_crontab
  tags: 
    - iam-cronjob

- name: debug check crontab
  debug:
    msg: "{{check_crontab}}"
  tags: 
    - iam-cronjob
