- name: Cronjob Check Daily Aide
  cron:
      name: "Aide Check Daily"
      minute: "23"
      hour: "22"
      day: "*"
      month: "*"
      weekday: "*"
      job: /usr/sbin/aide --check
  tags: 
    - file_integrity
    - cronjob
    - aide_crontab

- name: crontab ram flush
  cron:
    name: "ram flush"
    job: "bash /opt/crontab/ram_flush.sh"
  register: check_crontab
  tags: 
    - ram_flush
    - cronjob

- name: debug check crontab
  debug:
    msg: "{{check_crontab}}"
  tags: 
   - ram_flush
   - cronjob
