---
- name: Install AIDE on RPM Packages
  yum:
      name: aide
      state: present
  when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags: 
    - file_integrity
    - install_aide_rpm


- name: Install AIDE on DEB Packages
  apt:
      name: aide
      state: present
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
  tags: 
    - file_integrity
    - install_aide_deb


- name: Iniziate Database Aide
  shell: aide --init
  tags: 
    - file_integrity
    - aide_init_db

- name: Copy Database to Lib
  copy: 
      src: /var/lib/aide/aide.db.new.gz
      dest: /var/lib/aide/aide.db.gz
      remote_src: true
  tags: 
    - file_integrity
    - aide_copy_db




