---
- sysctl:
    name: vm.swappiness
    value: '1'
    reload: yes
    state: present
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.dmesg_restrict
    value: '1'
    reload: yes
    state: present
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.kptr_restrict
    value: '2'
    reload: yes
    state: present
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.yama.ptrace_scope
    value: '1'
    reload: yes
    state: present
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: '0'
    reload: yes
    state: present
  tags: 
    - iam-kernel

- sysctl:
    name: fs.protected_fifos
    value: '2'
    reload: yes
    state: present
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: fs.protected_regular
    value: '2'
    reload: yes
    state: present
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.modules_disabled
    value: '1'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.perf_event_paranoid
    value: '3'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.core.bpf_jit_harden
    value: '2'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: '0'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.conf.all.log_martians
    value: '1'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: '0'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.conf.default.accept_redirects 
    reload: yes 
    state: present 
    value: 0 
  ignore_errors: true
  tags: 
    - iam-kernel
      
- sysctl:
    name: net.ipv4.conf.default.log_martians 
    reload: yes 
    state: present 
    value: 1 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv6.conf.all.accept_redirects 
    reload: yes 
    state: present 
    value: 0 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv6.conf.default.accept_redirects 
    reload: yes 
    state: present 
    value: 0 
  ignore_errors: true
  tags: 
    - iam-kernel


#### ANTI DDOS KERNEL SETTING ###

- sysctl:
    name: kernel.printk 
    reload: yes 
    state: present 
    value: '4 4 1 7' 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.panic 
    reload: yes 
    state: present 
    value: 10
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.sysrq
    value: '0'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.shmmax
    value: '4294967296'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.shmall
    value: '4194304'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.core_uses_pid
    value: '1'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.msgmnb 
    value: '65536'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.msgmax 
    value: '65536'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: vm.dirty_ratio
    value: 90
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: vm.dirty_background_ratio
    value: 5
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: fs.file-max
    value: '2097152'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.core.rmem_default
    value: '31457280'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.core.netdev_max_backlog 
    value: '262144'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.core.rmem_max
    value: '67108864'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.core.wmem_default
    value: '31457280'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.core.somaxconn
    value: '65535'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.core.optmem_max
    value: '25165824'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.neigh.default.gc_thresh1
    value: '4096'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.neigh.default.gc_thresh2
    value: '8192'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.neigh.default.gc_thresh3
    value: '16384'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.neigh.default.gc_interval
    value: '5'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.neigh.default.gc_stale_time
    value: '120'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.netfilter.nf_conntrack_max
    value: '10000000'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.netfilter.nf_conntrack_tcp_loose
    value: '0'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_established
    value: '1800'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_close
    value: '10'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_close_wait
    value: '10'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_fin_wait
    value: '20'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_last_ack
    value: '20'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_syn_recv
    value: '20'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_syn_sent
    value: '20'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_time_wait
    value: '10'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: '0'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.ip_local_port_range
    value: '1024 65000'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.ip_no_pmtu_disc 
    value: '1'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.route.flush  
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.route.max_size 
    value: '8048576'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: '8048576'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses  
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.tcp_congestion_control 
    value: 'htcp'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.tcp_mem 
    value: '65536 131072 262144'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.udp_mem 
    value: '65536 131072 262144'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.tcp_rmem
    value: '4096 87380 33554432'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.udp_rmem_min
    value: '16384'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.tcp_wmem
    value: '4096 87380 33554432'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.udp_wmem_min 
    value: '16384'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_max_tw_buckets 
    value: '1440000'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_tw_recycle 
    value: '0'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_tw_reuse 
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_max_orphans 
    value: '400000'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_window_scaling 
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_rfc1337 
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_syncookies 
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_synack_retries 
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_syn_retries 
    value: '2'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_max_syn_backlog 
    value: '16384'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_timestamps 
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_sack 
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_fack 
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_ecn 
    value: '2'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_fin_timeout 
    value: '10'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_keepalive_time 
    value: '600'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_keepalive_intvl 
    value: '60'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_keepalive_probes 
    value: '10'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.tcp_no_metrics_save 
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.ip_forward 
    value: '0'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.conf.all.accept_redirects 
    value: '0'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.conf.all.send_redirects 
    value: '0'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.conf.all.accept_source_route 
    value: '0'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel


- sysctl:
    name: net.ipv4.conf.all.rp_filter 
    value: '1'
    reload: yes
    state: 
  ignore_errors: true
  tags: 
    - iam-kernel
