---
- sysctl:
    name: vm.swappiness
    value: '1'
    reload: yes
    state: present
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.dmesg_restrict
    value: '1'
    reload: yes
    state: present
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.kptr_restrict
    value: '2'
    reload: yes
    state: present
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.yama.ptrace_scope
    value: '1'
    reload: yes
    state: present
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: '0'
    reload: yes
    state: present
  tags: 
    - iam-kernel

- sysctl:
    name: fs.protected_fifos
    value: '2'
    reload: yes
    state: present
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: fs.protected_regular
    value: '2'
    reload: yes
    state: present
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.modules_disabled
    value: '1'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: kernel.perf_event_paranoid
    value: '3'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.core.bpf_jit_harden
    value: '2'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: '0'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.conf.all.log_martians
    value: '1'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: '0'
    reload: yes
    state: present
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv4.conf.default.accept_redirects 
    reload: yes 
    state: present 
    value: 0 
  ignore_errors: true
  tags: 
    - iam-kernel
      
- sysctl:
    name: net.ipv4.conf.default.log_martians 
    reload: yes 
    state: present 
    value: 1 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv6.conf.all.accept_redirects 
    reload: yes 
    state: present 
    value: 0 
  ignore_errors: true
  tags: 
    - iam-kernel

- sysctl:
    name: net.ipv6.conf.default.accept_redirects 
    reload: yes 
    state: present 
    value: 0 
  ignore_errors: true
  tags: 
    - iam-kernel
