---
- sysctl:
    name: vm.swappiness
    value: '5'
    state: present
  tags: 
    - kernel

- sysctl:
    name: kernel.dmesg_restrict
    value: '1'
    state: present
  tags: 
    - kernel

- sysctl:
    name: kernel.kptr_restrict
    value: '2'
    state: present
  tags: 
    - kernel

- sysctl:
    name: kernel.sysrq
    value: '0'
    state: present
  tags: 
    - kernel

- sysctl:
    name: kernel.yama.ptrace_scope
    value: '1'
    state: present
  tags: 
    - kernel

- sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: '0'
    state: present
  tags: 
    - kernel

- sysctl:
    name: net.ipv4.conf.all.log_martians
    value: '1'
    state: present
  tags: 
    - kernel

- sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: '0'
    state: present
  tags: 
    - kernel

- sysctl:
    name: net.ipv4.conf.default.accept_redirects # required. The dot-separated path (aka I(key)) specifying the sysctl variable.
    reload: yes # not required. If C(yes), performs a I(/sbin/sysctl -p) if the C(sysctl_file) is updated. If C(no), does not reload I(sysctl) even if the C(sysctl_file) is updated.
    state: present # not required. choices: present;absent. Whether the entry should be present or absent in the sysctl file.
    sysctl_set: no # not required. Verify token value with the sysctl command and set with -w if necessary
    ignoreerrors: no # not required. Use this option to ignore errors about unknown keys.
    sysctl_file: /etc/sysctl.conf # not required. Specifies the absolute path to C(sysctl.conf), if not C(/etc/sysctl.conf).
    value: 0 # not required. Desired value of the sysctl key.
  tags: 
    - kernel
      
- sysctl:
    name: net.ipv4.conf.default.log_martians # required. The dot-separated path (aka I(key)) specifying the sysctl variable.
    reload: yes # not required. If C(yes), performs a I(/sbin/sysctl -p) if the C(sysctl_file) is updated. If C(no), does not reload I(sysctl) even if the C(sysctl_file) is updated.
    state: present # not required. choices: present;absent. Whether the entry should be present or absent in the sysctl file.
    sysctl_set: no # not required. Verify token value with the sysctl command and set with -w if necessary
    ignoreerrors: no # not required. Use this option to ignore errors about unknown keys.
    sysctl_file: /etc/sysctl.conf # not required. Specifies the absolute path to C(sysctl.conf), if not C(/etc/sysctl.conf).
    value: 1 # not required. Desired value of the sysctl key.
  tags: 
    - kernel

- sysctl:
    name: net.ipv6.conf.all.accept_redirects # required. The dot-separated path (aka I(key)) specifying the sysctl variable.
    reload: yes # not required. If C(yes), performs a I(/sbin/sysctl -p) if the C(sysctl_file) is updated. If C(no), does not reload I(sysctl) even if the C(sysctl_file) is updated.
    state: present # not required. choices: present;absent. Whether the entry should be present or absent in the sysctl file.
    sysctl_set: no # not required. Verify token value with the sysctl command and set with -w if necessary
    ignoreerrors: no # not required. Use this option to ignore errors about unknown keys.
    sysctl_file: /etc/sysctl.conf # not required. Specifies the absolute path to C(sysctl.conf), if not C(/etc/sysctl.conf).
    value: 0 # not required. Desired value of the sysctl key.
  tags: 
    - kernel

- sysctl:
    name: net.ipv6.conf.default.accept_redirects # required. The dot-separated path (aka I(key)) specifying the sysctl variable.
    reload: yes # not required. If C(yes), performs a I(/sbin/sysctl -p) if the C(sysctl_file) is updated. If C(no), does not reload I(sysctl) even if the C(sysctl_file) is updated.
    state: present # not required. choices: present;absent. Whether the entry should be present or absent in the sysctl file.
    sysctl_set: no # not required. Verify token value with the sysctl command and set with -w if necessary
    ignoreerrors: no # not required. Use this option to ignore errors about unknown keys.
    sysctl_file: /etc/sysctl.conf # not required. Specifies the absolute path to C(sysctl.conf), if not C(/etc/sysctl.conf).
    value: 0 # not required. Desired value of the sysctl key.
  tags: 
    - kernel
