- name: "Setting Limits Configuration File limits.conf"
  become: 'yes'
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - limits

- name: "[DEB Based] Setting Coredump"
  become: 'yes'
  template:
    src: coredump.conf.j2
    dest: /etc/systemd/coredump.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  tags:
    - iam-limits
