- name: limits.conf
  become: 'yes'
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - limits

- name: coredump.conf
  become: 'yes'
  template:
    src: coredump.conf.j2
    dest: /etc/systemd/coredump.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - iam-limits
 
...