- name: Install Auditd on RPM Packages
  yum:
      name: audit
      state: present 
  when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags: 
    - iam-logging 


- name: Install Auditd on DEB Packages
  apt:
      name: auditd
      state: present 
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
  tags: 
    - iam-logging 

- name: Copy File Configuration Auditd Luneareth Rules
  copy:
    src: general-auditd.rules
    dest: /etc/audit/rules.d/general-auditd.rules
    owner: root
    group: root
    mode: 0644
  notify: "start auditd" 
  tags: 
    - iam-logging


  





