
- name: Ensure rsyslog is installed
  package:
    name: rsyslog
    state: present
  ignore_errors: yes
  tags:
    - iam-logs

- name: Ensure rsyslog Service is enabled
  service:
    name: rsyslog
    enabled: yes
  ignore_errors: yes
  tags:
    - iam-logs
    - logs-enable_service_rsyslog


- name: Ensure logging is configured
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  ignore_errors: yes
  tags:
    - iam-logs
    - logs-copy_config_rsyslog


- name: Ensure rsyslog default file permissions configured
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$FileCreateMode (0640)?'
    line: "$FileCreateMode 0640"
  ignore_errors: yes
  tags:
    - iam-logs
    - logs-rsyslog_permissions


- name: Ensure journald is configured to send logs to rsyslog
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?ForwardToSyslog=(yes|no)"
    line: ForwardToSyslog=yes
  tags:
    - iam-logs
    - logs-journald_send_to_rsyslog


- name: Ensure journald is configured to compress large log files
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?Compress=(yes|no)"
    line: Compress=yes
  tags:
    - iam-logs
    - logs-rsyslog_compress_large_logs


- name: Ensure journald is configured to write logfiles to persistent disk
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?Storage=(auto|persistent)"
    line: Storage=persistent
  notify:
    - restart systemd-journald
  tags:
    - iam-logs
    - logs-rsyslog_write_persistent_disk


- name: Ensure permissions on all logfiles are configured
  shell: |
    find /var/log -type f -exec chmod g-wx,o-rwx "{}" + -o -type d -exec chmod g-w,o-rwx "{}" +
  register: output_4_2_3
  changed_when: output_4_2_3.stdout_lines | length > 0
  tags:
    - iam-logs
    - logs-fix_all_permission_logs


- name: Ensure logrotate is configured
  replace:
    path: /etc/logrotate.d/rsyslog
    regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
    replace: "\\1{{ logrotate_policy }}"
  ignore_errors: true
  tags:
    - iam-logs
    - logs-configured_logrotate


- name: Ensure logrotate assigns appropriate permissions
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: "^create"
    line: "create 0640 root utmp"
  notify:
    - 'restart systemd-journald'
  ignore_errors: true
  tags:
    - iam-logs
    - logs-journald_Permissions
