- name: Copy ntp-deb.conf
  become: 'yes'
  template:
    src: ntp-deb.conf.j2
    dest: /etc/systemd/timesyncd.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  notify:
    - reload systemd
  ignore_errors: true
  tags:
    - iam-ntp
    - ntp-deb

- name: register timesyncd status
  command: systemctl status systemd-timesyncd  
  register: timesyncd_status
  changed_when: false
  failed_when: false
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  tags:
    - iam-ntp
    - ntp-deb

- name: register timedatectl show
  command: timedatectl show
  register: timedatectl_show
  changed_when: timedatectl_show.stdout.find('NTPSynchronized=yes') == -1 and timesyncd_status.rc == 0
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  tags:
    - iam-ntp
    - ntp-deb

- name: timedatectl set-ntp
  become: 'yes'
  command: timedatectl set-ntp true
  when: 
    - ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  tags:
    - iam-ntp
    - ntp-deb


- name: set timezone
  shell: timedatectl set-timezone UTC
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat' 
  tags:
    - iam-ntp
    - ntp-rpm

- name: Install NTP
  package: 
    name: ntp 
    state: present
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat' 
  tags:
    - iam-ntp
    - ntp-rpm

- name: Copy over the NTP configuration
  template:
    src: ntp-deb.conf.j2 
    dest: /etc/ntp.conf
  notify:
    - restart ntpd
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat' 
  tags:
    - iam-ntp
    - ntp-rpm

- name: Sync time initialy
  shell: ntpdate 0.centos.pool.ntp.org
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat' 
  tags:
    - iam-ntp
    - ntp-rpm

- name: Sync hwclock
  shell: hwclock -w
  tags:
    - iam-ntp

