### CENTOS or REDHAT
- name: "[RPM Based] Install epel-release Repo"
  package:
    name: epel-release
    state: present
    enablerepo: "epel,powertools"
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat' 
  ignore_errors: yes
  tags:
    - iam-packages
    - packages-rpm
    - rpm-epel_release

    
- name: "[RPM Based] Upgrade all packages to Latest"
  package:
    name: '*'
    state: latest
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat' 
  ignore_errors: yes
  tags:
    - iam-packages
    - packages-rpm
    - rpm-upgrade


- name: "[RPM Based] Packages Installation Needs"
  become: 'yes'
  package:
    name: "{{ packages_rpm }}"
    state: present
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  ignore_errors: yes
  tags:
    - iam-packages
    - packages-rpm
    - rpm-install_packages_needs


##### DEBIAN or UBUNTU
- name: "[DEB Based] Update Repository List"
  apt:
    update_cache: yes
  when: ansible_os_family == 'Ubuntu' Or ansible_os_family == 'Debian'
  ignore_errors: yes
  tags:
    - iam-packages
    - packages-deb
    - deb-update

    
- name: "[DEB Based] Update all packages to the latest version"
  apt:
    upgrade: dist
  when: ansible_os_family == 'Ubuntu' Or ansible_os_family == 'Debian'
  ignore_errors: yes
  tags:
    - iam-packages
    - packages-deb
    - deb-upgrade


- name: "[DEB Based] Package Installation Needs"
  become: 'yes'
  apt:
    name: "{{ packages_deb }}"
    state: present
  when: ansible_os_family == 'Ubuntu' Or ansible_os_family == 'Debian'
  ignore_errors: yes
  tags:
    - iam-packages
    - packages-deb
    - deb-install_packages_needs