- name: Install epel-release
  package:
    name: epel-release
    state: present
    enablerepo: "epel,powertools"
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat' 
  ignore_errors: yes
  tags:
    - iam-packages

- name: RPM Package Installation
  become: 'yes'
  package:
    name: "{{ packages_rpm }}"
    state: present
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags:
    - iam-packages

- name: Upgrade all packages
  package:
    name: '*'
    state: latest
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat' 
  ignore_errors: yes
  tags:
    - iam-packages



# For Packages DEB Based


    
