---
- name: Copy Public Key
  authorized_key:
    user: "{{ item.name }}"
    state: present
    manage_dir: yes
    key: "{{ item.pubkey }}"
  with_items:
          - {name: luneareth, pubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDodQhDnNzGF7EL8ORDyTpFhRdP7aofCqy+Z4YLE99onTK54GN59X07kzI/kpwH7zf5yMsaEwEqzZEDT8bW0c5pW0recah11dDOifWI355Z7Oy5sSKB7wZ+1QaKmFmL++8+Gh2P7GXyA009xP6EEDjLaRKudnVNJ79d6dEl0kAFJ5tan6oPtxZeLay8mJBOhMnMcVzWkCS+D/dFxmHBCWdDj9fD+cIZy9zYrw+KpMUozPEYMvvOcTcZFop8BU88MQ0IthNyUW9HtjcRtLSyw1FoS9wsZFFCMzB0lVuYfb119VJo5yarYITrg5ooGKyr0qxW+PhzFoWgQpXwFNPm7jVZ wajatmaka@gmail.com}
  tags: public_key