---
- name: Copy Public Key
  authorized_key:
    user: "{{ item.name }}"
    state: present
    manage_dir: yes
    key: "{{ item.pubkey }}"
  with_items:
          - {name: luneareth, pubkey: "{{ public_key }}" }
  tags: public_key