
- name: check to see if we need a reboot
  command: needs-restarting -r
  register: is_reboot
  ignore_errors: yes
  tags:
    - reboot

- name: display is_reboot
  debug:
    var: is_reboot.rc
  tags:
    - reboot

- name: Reboot Server if Necessary
  command: shutdown -r now "Ansible Updates Triggered"
  become: true
  async: 30
  poll: 0
  when: is_reboot.rc == 1 
  tags:
    - reboot

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  tags:
    - reboot

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true and ansible_os_family == "Debian"
  tags:
    - reboot

