---
- name: SELinux security policy
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^SELINUX=.*'
    line: 'SELINUX={{ SELINUX }}'
    state: present
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS' 
  tags: iam-selinux

- name: set SELinux type
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^SELINUXTYPE.*'
    line: 'SELINUXTYPE={{ SELINUXTYPE }}'
    state: present
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS' 
  tags: iam-selinux