- name: Create Group Monit
  group:
    name: monit
    state: present
  tags: user

- name: Adduser admin
  user:
    name: "{{ item }}"
    groups: wheel,monit
    shell: /bin/bash
    append: yes
  with_items:
    - "{{user_admin}}"
  when: ansible_os_family == "RedHat"
  tags: CreateUserGlobal
  

- name: Adduser Global to Monit Group
  user:
    name: "{{ item }}"
    groups: monit
    shell: /bin/bash
    create_home: yes
    home: /app
    append: yes
  with_items:
    - "{{user_app}}"
  when: ansible_os_family == "RedHat"
  tags: AddUserToMonit
