- name: Create Group Monit 
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - monit
  tags: iam-user_and_group


- name: Adduser admin and assign to Monit Wheel Group RPM Based
  user:
    name: "{{ item }}"
    groups: wheel,monit
    shell: /bin/bash
    append: yes
  with_items:
    - "{{user_admin}}"
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags: iam-user_and_group
  

- name: Adduser App and assign to Monit Group RPM Base
  user:
    name: "{{ item }}"
    groups: wheel,monit
    shell: /bin/bash
    create_home: yes
    home: /app
    state: present
    append: yes
  with_items:
    - "{{user_app}}"
  when:  ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags: iam-user_and_group

