- name: Create Group Monit
  group:
    name: monit
    state: present
  tags: user

- name: Adduser Global
  user:
    name: "{{ item }}"
    groups: wheel,monit
    shell: /bin/bash
    append: yes
  with_items:
    - luneareth
    - app
  when: ansible_os_family == "RedHat"
  tags: CreateUserGlobal
  

- name: Adduser Global to Monit Group
  user:
    name: "{{ item }}"
    groups: monit
    shell: /bin/bash
    append: yes
  with_items:
    - luneareth
    - app
  when: ansible_os_family == "RedHat"
  tags: AddUserToMonit
