- name: "[RPM Based] Create User Administrator (sudo access)"
  user:
    name: "{{ item.user }}"
    groups: wheel
    shell: /bin/bash
    create_home: yes
    home: "{{ item.home }}"
    append: yes
  with_items:
      - {user: "{{ user_admin }}", home: "/home/{{ user_admin }}" }
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS' 
  tags: 
  - iam-user_and_group
  - user_and_group-Create_User_Admin

- name: "[RPM Based] Create User Other User RPM Based"
  user:
    name: "{{ item.user }}"
    shell: /bin/bash
    create_home: yes
    home: "{{ item.home }}"
    append: yes
  with_items:
      - {user: "{{ user_other }}", home: "/{{ user_other }}" }
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS' 
  tags: 
  - iam-user_and_group
  - user_and_group-Create_User_Other

- name: "[DEB Based] Create User Administrator (sudo access)"
  user:
    name: "{{ item.user }}"
    groups: sudo
    shell: /bin/bash
    create_home: yes
    home: "{{ item.home }}"
    append: yes
  with_items:
      - {user: "{{ user_admin }}", home: "/home/{{ user_admin }}" }
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  tags: 
  - iam-user_and_group
  - user_and_group-Create_User_Admin


- name: "[DEB Based] Create User Other User DEB Based"
  user:
    name: "{{ item.user }}"
    shell: /bin/bash
    create_home: yes
    home: "{{ item.home }}"
    append: yes
  with_items:
      - {user: "{{ user_other }}", home: "/{{ user_other }}" }
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  tags: 
  - iam-user_and_group
  - user_and_group-Create_User_Other

### GROUP FOR SSH ACCESS
- name: Ensure group admin
  group:
    name: admin
    state: present
  tags:
  - iam-user_and_group
  - user_and_group-Create_Group_Admin

### ASSIGN USER TO GROUP ADMIN
- name: adding existing user to group admin
  user:
    name: "{{ item.user }}"
    groups: admin
    append: yes
  become: yes
  with_items:
  - "{{ user_other }}"
  - "{{ user_admin }}"