- name: Create Group Monit
  group:
    name: monit
    state: present
  tags: user_and_group

- name: Adduser admin and assign to Monit Wheel Group
  user:
    name: "{{ item }}"
    groups: wheel,monit
    shell: /bin/bash
    append: yes
  with_items:
    - "{{user_admin}}"
  tags: user_and_group
  

- name: Adduser App and assign to Monit Group
  user:
    name: "{{ item }}"
    groups: monit
    shell: /bin/bash
    create_home: yes
    home: /app
    append: yes
  with_items:
    - "{{user_app}}"
  tags: user_and_group
